### ISSUE TITLE
pm2 issue when installing?

### ISSUE THREAD

**Issue by DrBlackross** [turtlecoin/turtlecoind-ha#12]
npm WARN enoent ENOENT: no such file or directory, open '/home/drblackross/turtlecoin/package.json'
npm WARN turtlecoind-ha@0.14.1 requires a peer of @pm2/io@^4.2.4 but none was installed.
npm WARN turtlecoin No description
npm WARN turtlecoin No repository field.
npm WARN turtlecoin No README data
npm WARN turtlecoin No license field.

**Comment by zpalmtree** [comment]
It's an optional dependency
