### ISSUE TITLE
After several daemon restart DB got corrupted

### ISSUE THREAD

**Issue by angelobpool** [turtlecoin/turtlecoind-ha#8]
Yesterday I got several times:
>Daemon is not passing checks...: RequestError: Error: ESOCKETTIMEDOUT

After several of these errors consecutively the daemon got stopped and restarted as expected, I do not know what coused a so frequent succession of errors, but then after many restart distributed along the day something went wrong and the DB got corrupted, and I got in a loop of:

>Thu, 04 Apr 2019 15:40:42 GMT: TurtleCoind is waiting for connections at 1377842 @ 5383206514 - 179440217 H/s
>Thu, 04 Apr 2019 15:40:53 GMT: Daemon is not passing checks...: RequestError: Error: ESOCKETTIMEDOUT
>Thu, 04 Apr 2019 15:41:03 GMT: Daemon is not passing checks...: RequestError: Error: ESOCKETTIMEDOUT
>Thu, 04 Apr 2019 15:41:13 GMT: Daemon is not passing checks...: RequestError: Error: ESOCKETTIMEDOUT
>Thu, 04 Apr 2019 15:41:22 GMT: RequestError: Error: ESOCKETTIMEDOUT
>Thu, 04 Apr 2019 15:41:23 GMT: TurtleCoind is not responding... stopping process...
>Thu, 04 Apr 2019 15:41:23 GMT: Daemon is not passing checks...: RequestError: Error: ESOCKETTIMEDOUT
>Thu, 04 Apr 2019 15:41:27 GMT: Error in child process...: Error: read EIO
>Thu, 04 Apr 2019 15:41:27 GMT: TurtleCoind is not responding... stopping process...
>Thu, 04 Apr 2019 15:41:29 GMT: TurtleCoind has closed (exitcode: undefined)... restarting process...
>Thu, 04 Apr 2019 15:41:29 GMT: Database LOCK file exists...
>Thu, 04 Apr 2019 15:41:29 GMT: Deleted the DB LOCK File at: /home/pool/.TurtleCoin/DB/LOCK
>Thu, 04 Apr 2019 15:41:34 GMT: Attempting to start turtlecoind-ha...
>Thu, 04 Apr 2019 15:41:34 GMT: TurtleCoind has started... /home/pool/cores/turtlecoin/build/src/TurtleCoind --data-dir $
>Thu, 04 Apr 2019 15:41:35 GMT: Error in child process...: Error: read EIO
>Thu, 04 Apr 2019 15:41:35 GMT: TurtleCoind is not responding... stopping process...
>Thu, 04 Apr 2019 15:41:37 GMT: TurtleCoind has closed (exitcode: undefined)... restarting process...
>Thu, 04 Apr 2019 15:41:37 GMT: Database LOCK file exists...
>Thu, 04 Apr 2019 15:41:37 GMT: Deleted the DB LOCK File at: /home/pool/.TurtleCoin/DB/LOCK
>Thu, 04 Apr 2019 15:41:42 GMT: Attempting to start turtlecoind-ha...
>Thu, 04 Apr 2019 15:41:42 GMT: TurtleCoind has started... /home/pool/cores/turtlecoin/build/src/TurtleCoind --data-dir $ 
>Thu, 04 Apr 2019 15:41:42 GMT: Error in child process...: Error: read EIO
>Thu, 04 Apr 2019 15:41:42 GMT: TurtleCoind is not responding... stopping process...
>Thu, 04 Apr 2019 15:41:44 GMT: TurtleCoind has closed (exitcode: undefined)... restarting process...

I started the daemon manually to find out that the DB was corrupted, and I had to restore the blockchain.
(I'm using turtlecoind v0.13.0, and I have a pool running on this node other than exposing the node publicly)

**Comment by brandonlehmann** [comment]
First thing's first. Yesterday we saw a high influx of fusion transactions that hit the network as a result of normal network operations. Unfortunately, a high influx of transactions will cause some systems to lag and/or not respond to RPC requests (some of the checks performed by this package) in a timely manner. To allow the daemon more time to respond to such checks, you can extend the timeouts, number of failed cycles, etc in the `service.js` to customize it to your system.

In regard to the database corruption, take a look at the open PR over at https://github.com/turtlecoin/turtlecoin/pull/769 that may allow you to recover from such corruption more quickly in the future.

**Comment by codeknox** [comment]
Just to let you guys know, I used the `--rewind BLOCK_NUMBER` trick and it saved me!
It was the second try to sync (with checkpoints) on v14 and I was getting crazy.

Thanks for the new option.

BTW, I used `block number failing to save - 1`

**Comment by brandonlehmann** [comment]
Give the latest development copy of TurtleCoin a go. It now includes a `--rewind-to-height` feature to allow you to recover from this.
